// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARiHn_HvnRKk02nMt_XoT8Nci8KrjUfuA',
    appId: '1:54939419987:web:ff42a644041fff30d80da6',
    messagingSenderId: '54939419987',
    projectId: 'vikalp-913f1',
    authDomain: 'vikalp-913f1.firebaseapp.com',
    storageBucket: 'vikalp-913f1.appspot.com',
    measurementId: 'G-M8JVTQ5BFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw8BkSg_Xl8AIGGEuXi47vrtZpIhmmBAs',
    appId: '1:54939419987:android:81ffce1cf01934a2d80da6',
    messagingSenderId: '54939419987',
    projectId: 'vikalp-913f1',
    storageBucket: 'vikalp-913f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnwA7bjescIIQUgp9QYK4CLJOM9BO4dBU',
    appId: '1:54939419987:ios:b2c73db4c4029b7cd80da6',
    messagingSenderId: '54939419987',
    projectId: 'vikalp-913f1',
    storageBucket: 'vikalp-913f1.appspot.com',
    iosClientId: '54939419987-15updojc1untduijj4ha4nefoa9vuafq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vikalp',
  );
}
